# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.TextField(max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
